### PR TITLE
Update README.brazilian-portuguese.md

### PR DESCRIPTION
**Pull request by Francozeira**
Ortographic errors correction and  transtalation of non-translated english paragraph on portuguese translation version

### CODE REVIEW

**Comment by marcelosdm** [comment]
@Francozeira Yeeeah!! Great job!!

By the way, I'd love if you could join me to translate the other files to Brazilian Portuguese. What do you think? 😃

**Comment by Francozeira** [comment]
Sure @marcelosdm, would be glad to help on this project.
How do we proceed?

**Comment by marcelosdm** [comment]
So, welcome aboard @Francozeira !

Well, as you can see, I translated the **README** page. Now, we've got all the sections to dive in and do our work!

I would suggest for you to pick up a section, and translate its _Read More_ contents.

For example, [Structure by Components](https://github.com/i0natan/nodebestpractices/blob/master/sections/projectstructre/breakintcomponents.md)

What do you think?

**Comment by Francozeira** [comment]
Deal! 
I'll start working on that, and will keep contact so can work this through

**Comment by marcelosdm** [comment]
> Deal!
> I'll start working on that, and will keep contact so can work this through

Awsome! 👍

Reach me anytime you need!

**Comment by Francozeira** [comment]
@marcelosdm i was just now finishing translation of Structure by Components and i saw Marcelo's upload of translated version of Structure by Components and other files, just to know, how is the usual work time for each file? i would like to help on this, but may not be able to be onto this project depending on job/college duties, also, do you have another way so we can chat other than this issue?

**Pull request merged**
