### PR TITLE
Changed (b) to (2) and made it easier to read

### PR DESCRIPTION
**Pull request by ymhtut**

### CODE REVIEW

**Comment by BrunoScheufler** [comment]
@ymhtut awesome stuff! Would you like to add yourself to our 'thank you notes' section in the README? If so, just add yourself (don't forget the comma 😄) and push to the same branch as your changes 👍

**Comment by i0natan** [comment]
@ymhtut, great stuff, thanks.

would you like to join and collaborate with us on further improving and enriching the guide?

**Comment by ymhtut** [comment]
@i0natan Yes, I would love to.

**Comment by i0natan** [comment]
@ymhtut great to hear! 

any specific topic preferences/skills?

I'll share soon few future enhancements we want to perform and let you choose your preferred topic.

**Comment by ymhtut** [comment]
@i0natan Project structuring, Error Handling and Testing would be my preferred topics.

**Pull request merged**
