### PR TITLE
Added initial compression copy

### PR DESCRIPTION
**Pull request by TheHollidayInn**
Here is my initial draft for using compression. It's definitely rough, so comments are most welcome :D

### CODE REVIEW

**Comment by i0natan** [comment]
@TheHollidayInn I suggest to include this item as part of our generic bullet (each section has a generic bullet "Other advice") and not as an independent one because:

- We have a recommendation in our guide not to store static assets in Node. It's not common and usually slower to compress API responses
- If you do host static assets, then it's usually recommended to perform the compression outside of Node
- It's not an advice that relates specifically to Node rather to any web platform

Thoughts?

**Comment by TheHollidayInn** [comment]
Yeah, I think that sounds good! This one is small as well.

**Comment by TheHollidayInn** [comment]
Should I create the generic section?

**Comment by i0natan** [comment]
> Should I create the generic section?

@TheHollidayInn Good idea, just keep the same formatting as 6.5 (security generic). Also, before that let's open an issue and put together few ideas (it doesn't make sense to open a generic bullet for 1 item)

**Pull request closed without merging**
