### PR TITLE
Russian translation

### PR DESCRIPTION
**Pull request by oshliaer**
## Intro

I can't get a lot of time. And I don't know the tools that will help me synchronize future changes. Therefore, I will add this part to the repository.

## Translation schedule

7/3/19

## Marks

Expected date: 7/5/19
Updated: 7/3/19

### CODE REVIEW

**Comment by i0natan** [comment]
@oshliaer Looks like an outstanding work 💃 

Why are hundreds of files changed?

You mentioned 'Don't merge now, please.', shouldn't we?

**Comment by oshliaer** [comment]
@i0natan, 

> Why are hundreds of files changed?

I pulled [this branch ⎇ _russian-translation_](https://github.com/i0natan/nodebestpractices/tree/russian-translation) because I thought that there would be significant changes. But I did not find anything. This is just a sync. Should I just push to a new branch?

> You mentioned 'Don't merge now, please.', shouldn't we?

I started without a full research of Russian maintainers. And I set myself a challenge that I want to perform before the 5th :smile: 

As you can see now I finished README translation. Please review and merge if it's possible.

**Comment by oshliaer** [comment]
@i0natan  I made a little resume #105

**Comment by i0natan** [comment]
@sagirk Just noted that you're handling Russian, can you take care to merge @oshliaer amazing work?

If calendar too busy, LMK and I'll help

/remind me in 2 days

**Comment by i0natan** [comment]
@oshliaer I'm now handling the Russian translation (Sagir is now focused on some other challenge will be on a break for few months), latest commit is merged.

Let me know how can I help in pushing forward?

**Pull request merged**
