### PR TITLE
Add Keymetrics to APM section

### PR DESCRIPTION
**Pull request by Unitech**

### CODE REVIEW

**Comment by refack** [comment]
@Unitech thanks you for the contribution. I'd suggest you crop the screenshot to emphasise the features, maybe by zooming in on the header + 1 item, otherwise the details get drowned out, see it compared to the other two. Also IMHO writing 2-3 lines on what we're seeing will be a good precedent.
image

@idori @i0natan we should have a policy about vendor plugs
* Except anyone who submits a PR?
* Have some sort of gate (number of users, rank in google, number of letter in name, color of logo 🤷‍♂️ )
* Order in the list (ASCIIbetical?)

**Comment by Unitech** [comment]
ok! I wil do it

**Comment by Unitech** [comment]
Is it ok like that? I've cropped the right side of the screenshot so you can see more information

**Comment by Unitech** [comment]
Up!

**Comment by sagirk** [comment]
@Unitech @refack @i0natan Seems this PR has remained stalled for nearly a year now. I'm trying to clear the backlog one PR at a time. What can we do to move this closer to be mergeable?

**Comment by Unitech** [comment]
I will create a new PR about our new monitoring product, closing that one for now

**Comment by i0natan** [comment]
@js-kyle Assigning to you as it's related to devops (going by routing table)

See the [vendors section here](https://github.com/i0natan/nodebestpractices/blob/master/.operations/writing-guidelines.md)

**Pull request closed without merging**
