### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by vkaracic**
`An hierarchical JSON files that is grouped into section can overcome this issue` to:
`A hierarchical JSON file that is grouped into section can overcome this issue`.

### CODE REVIEW

**Comment by j-f1** [comment]
Maybe `grouped into sections`?

**Comment by vkaracic** [comment]
Correct. Can you squash the commits via Github?

**Comment by j-f1** [comment]
> Can you squash the commits via Github?

No, but most maintainers are fine with merging a multi-commit PR. In fact, they can even squash the commits while merging if they’d like.

**Comment by BrunoScheufler** [comment]
Thank you very much @vkaracic!

**Pull request merged**
