### PR TITLE
1.1 and 1.2 translated to Korean

### PR DESCRIPTION
**Pull request by uronly14me**
Hello, I translated 1.1 and 1.2 to Korean.
Please check them.

### CODE REVIEW

**Comment by uronly14me** [comment]
@Yitaek  Thanks, I fixed that.

**Comment by uronly14me** [comment]
@i0natan Hello, could you review my pull request or should I wait for Korean lead?

**Comment by hinco114** [comment]
@uronly14me 제가 작업하던 내용보다 더 번역을 잘하신것 같네요.
지금 제가 권한이 없어서 Review 나 Approve 할 수가 없습니다... 
Maybe @i0natan will Approve this PR.

**Comment by i0natan** [comment]
@uronly14me Sorry for the delay, looks awsome. Shall we merge to master as well (readers will see partial Koren content) or shall we wait for the entire translation?

@Yitaek Thanks! 👍 👍 👍

**Comment by uronly14me** [comment]
@i0natan Yes, please merge this to master! Thanks!

**Comment by i0natan** [comment]
@uronly14me This is handled with high priority, kindly wait few days

**Pull request merged**
