### PR TITLE
translation: add file sections/projectstructre/breakintcomponents.chinese.md

### PR DESCRIPTION
**Pull request by blackmatch**
Hello team,
I have tried my best to translate `breakintcomponents.md` to Chinese. Hope it can be useful.

### CODE REVIEW

**Comment by i0natan** [comment]
@blackmatch Thank you and welcome aboard 🌷 

We have a Chinese translation, this file is not translated over there?

cc @MattJin

**Comment by blackmatch** [comment]
@i0natan 

When I click the link as below:

image

I got a 404 page.

the link url is https://github.com/i0natan/nodebestpractices/blob/master/sections/projectstructre/breakintcomponents.chinese.md

I can't find the file on `/sections/projectstructre/breakintcomponents.chinese.md`, so I translate it.

If the file has been translated, plz skip this PR.

**Comment by MattJin** [comment]
@blackmatch Yes, it's translated. But the Chinese one was renamed as 'breakintcomponents.korean.md'. I will fix it.

**Comment by i0natan** [comment]
@blackmatch Thanks a bunch for the contribution.

@MattJin Consider getting help from @blackmatch when translating future sections?

**Comment by MattJin** [comment]
@blackmatch Would you like to join in the translation of other sections?

**Comment by blackmatch** [comment]
@MattJin Of course. I'll try my best.

**Comment by MattJin** [comment]
@blackmatch Great! Send you mail. Plz have a check.

**Pull request closed without merging**
