### PR TITLE
Fix Broken links (KOREAN)

### PR DESCRIPTION
**Pull request by ChangJoo-Park**
Almost all links are broken.
before translate this articles, I create files from english :)

### CODE REVIEW

**Comment by i0natan** [comment]
@ChangJoo-Park Thanks for improving 😸 

@uronly14me Can you help revise?

**Comment by uronly14me** [comment]
@i0natan OK, I will help him!
@ChangJoo-Park 안녕하세요 제가 도울수있는게 있을까요?

**Comment by ChangJoo-Park** [comment]
@uronly14me 안녕하세요 :)

이전 문서에서 빠져있는 문서들을 추가했거든요  리뷰 승인해주시면 시간날때마다 하나씩 한국어로 바꿀게요

**Comment by uronly14me** [comment]
@i0natan 
 I approved this request. Could you merge this request?

**Comment by i0natan** [comment]
@uronly14me - thanks 👍 

@ChangJoo-Park Awesome, assigning a flower here #421

**Pull request merged**
