### PR TITLE
Translate 3.3 bullet and others to Korean

### PR DESCRIPTION
**Pull request by uronly14me**
Hello @i0natan,

I have been translating Korean main file and as you said I think it is good to merge to master branch.
I have merged master to korean-translation-uronly14me branch once, so there may be conflicts.

Thanks for reviewing.

### CODE REVIEW

**Comment by i0natan** [comment]
@uronly14me Looks great!

@BrunoScheufler Any chance you can handle this? it requires first to PR this into the Koren branch, then rebase it (merge with the master), then PR to master and approve. An easy way to do this could be to createa new branch, based from the master of course, and just copy into it the proposed Korean files. Finally, just ensure that we have a Korean flag on the home page + credits to @uronly14me

**Comment by BrunoScheufler** [comment]
@i0natan I'll take on this!

**Comment by BrunoScheufler** [comment]
@uronly14me you can message me once everything is completed to your liking! I'll start the review and merge process then 👍

**Comment by uronly14me** [comment]
Hello @BrunoScheufler! I completed translation of section 3. You can merge it now because it might take times to translate other sections. I will translate them soon.

**Comment by BrunoScheufler** [comment]
@uronly14me awesome! I will look over it (just formally, because I can't really read it 😄) and start the process of merging it!

**Comment by uronly14me** [comment]
@BrunoScheufler I think at the first commit #a63d5f1 @i0natan moved chinese file to korean file

**Comment by BrunoScheufler** [comment]
@uronly14me oh I see, I think I get the reason behind it, could be due to his proposed way of merging new translations. Everything's fine, then 👍

**Pull request merged**
