### PR TITLE
Russian translation #3

### PR DESCRIPTION
**Pull request by oshliaer**
- [x] Production (some part of this)
- [x] Project Structure
- [x] Testing and Quality

### CODE REVIEW

**Comment by oshliaer** [comment]
@i0natan /done

**Comment by i0natan** [comment]
@oshliaer What is done? the 3 specified parts?

**Comment by oshliaer** [comment]
Yep!

Sorry it's a habit. In another repository we have a CI-bot which changes the issue status when I type '`/ done`'

Thanks for the merge! :fireworks:

**Comment by i0natan** [comment]
Looks like we can already merge it to the master and present content to Russian audience? which part approximately is not translated yet?

**Comment by oshliaer** [comment]
@i0natan 

#444 is the last part

**Pull request merged**
