### PR TITLE
Translated section 2 and corrected typos

### PR DESCRIPTION
**Pull request by DouglasMV**
Translated the Read More files from section 2: Error Handling.
Corrected some typos at the english version i found while translating.

### CODE REVIEW

**Comment by marcelosdm** [comment]
Wow!!! Such a great job @DouglasMV ! 👍

Thanks friend!

**Comment by DouglasMV** [comment]
Thanks!
Can i work on the section 6 Read More's or is there someone already doing that one?

**Comment by BrunoScheufler** [comment]
@DouglasMV would be best to ask @marcelosdm about the current progress :+1:

**Comment by marcelosdm** [comment]
> Thanks!
> Can i work on the section 6 Read More's or is there someone already doing that one?

Hey @DouglasMV ! It's all yours!!! 👏👏👏

Great job friend!

**Pull request merged**
