### PR TITLE
Update shuttingtheprocess.md

### PR DESCRIPTION
**Pull request by aecorredor**
Fix indentation for errorHandler() and add missing closing bracket.

### CODE REVIEW

**Comment by BrunoScheufler** [comment]
Awesome, that makes it much cleaner! Thanks for your contribution 👍

**Comment by aecorredor** [comment]
No problem, cheers!

**Comment by aecorredor** [comment]
@BrunoScheufler that'd be awesome! just added myself to the list 🥇 Thanks for creating this great repo man.

**Comment by BrunoScheufler** [comment]
I'll forward the thanks to @i0natan 🎉 Thanks for helping out 😄

**Comment by i0natan** [comment]
@brunoscheufler shall we maintain a list of people who contributed each month and assign flowers to all once each month (instead of updating each time)?

**Comment by BrunoScheufler** [comment]
@i0natan that might be a good idea, so you think of adding the flowers for all contributors once each month (for example at the end) instead of looking per-PR or occasion?

**Comment by i0natan** [comment]
@BrunoScheufler yes, sounds more efficient (1 update per month)

**Pull request merged**
