### PR TITLE
Update README.md - Added Pino to the suggested loggers list

### PR DESCRIPTION
**Pull request by lmammino**
Added Pino to the suggested loggers list (fastest one!)

### CODE REVIEW

**Comment by lmammino** [comment]
Btw, Pino is already mentioned in the full post dedicated to using a logger library.

**Comment by js-kyle** [comment]
Thanks @lmammino !

**Comment by i0natan** [comment]
@lmammino https://twitter.com/nodepractices/status/1158761084859367424

**Comment by lmammino** [comment]
Thanks for the shout out :) @i0natan

**Pull request merged**
