### PR TITLE
updated NPM => npm

### PR DESCRIPTION
**Pull request by js-kyle**

### CODE REVIEW

**Comment by js-kyle** [comment]
@BrunoScheufler For what is in master, yes. We might have added some more in the security branch, so we can perhaps check that as part of a final review

**Comment by BrunoScheufler** [comment]
@js-kyle yeah right, although its already good for now! Might be done as part of another PR later!

**Comment by i0natan** [comment]
@js-kyle @BrunoScheufler I love your keen eye for details :)

@js-kyle I think it's about time we add you to the repo collab + maintainers list, no?

**Comment by i0natan** [comment]
Adding to #183

**Pull request merged**
