### PR TITLE
Fixing some typos in dependencysecurity.md

### PR DESCRIPTION
**Pull request by vitordagamagodoy**
Just fixing some typos

### CODE REVIEW

**Comment by BrunoScheufler** [comment]
@vitordagamagodoy thanks for your help 💯

**Comment by vitordagamagodoy** [comment]
Thanks for helping a beginner to learn Node! :)

**Comment by i0natan** [comment]
@BrunoScheufler Asking only for future purposes so things won't fall between the cracks - Shouldn't we assign this to @js-kyle who's the security chief going by the routing table? anyway no one is assigned on this

**Comment by BrunoScheufler** [comment]
@i0natan as this is related to styling/grammar conventions, I think it's okay to assign it to an editor or proof-reader who can quickly validate the changes instead of assigning it to a content-related team member, because it's not about content changes but rather format and language 👍

**Comment by i0natan** [comment]
@BrunoScheufler You're 100% right

**Pull request merged**
