### PR TITLE
Fixed typos and optimized sentence syntax of sections

### PR DESCRIPTION
**Pull request by BrunoScheufler**

### CODE REVIEW

**Comment by i0natan** [comment]
@BrunoScheufler @idori is this the same PR we discussed yesterday or a new one?

**Comment by BrunoScheufler** [comment]
A new one! Although it does seem like the one from yesterday!

**Comment by idori** [comment]
Thanks for all the hard work @BrunoScheufler ! I'll go over it and merge

**Comment by BrunoScheufler** [comment]
Is it possible to become a collaborator in one point of time? I would love to help maintain this repository over time in content and styling!

**Comment by i0natan** [comment]
@BrunoScheufler based on your great contribution we would love to have you as part of the team. Can you kindly drop an email to: me %at% goldbergyoni.com?

**Pull request merged**
