### PR TITLE
[Chinese-translation]Complete the initial version

### PR DESCRIPTION
**Pull request by MattJin**

### CODE REVIEW

**Comment by i0natan** [comment]
@MattJin looks amazing. Just checking that no English file/link was affected.

@BrunoScheufler can you help me in going through the changed files and ensuring that the English version is in tact?

**Comment by MattJin** [comment]
@i0natan I compared with there two branches. No English files are changes. Plz have a check.

**Comment by i0natan** [comment]
@MattJin 

Unless you want to language-proof I can merge it into the master now. @idori will soon add links & flags from the home page so every visitor gets a link to the Chinese version.

Don't you want to add your name to the top of the Chinese page (Translated By:...)?

I want to take this opportunity thanks again for the contribution. Let's be in touch in bringing updates and other content to the Chinse community.

**Comment by MattJin** [comment]
@i0natan I will think about your suggestion. 

It's my pleasure to do this work and I learn a lot from it. I will continue to update and introduce them to the Chinese community.

**Pull request merged**
