### PR TITLE
Fix a typo :haircut_woman: 

### PR DESCRIPTION
**Pull request by oshliaer**
I think there is a typo.

```
, it becomes hairy to match other lines
```
to
```
, it becomes hard to match other lines
```

### CODE REVIEW

**Comment by BrunoScheufler** [comment]
I believe this one is actually intended 😄 While marked as informal, "hairy" should probably refer to "risky", "challenging" or "difficult" 👍 Thanks for having a closer look though 🙌

**Comment by oshliaer** [comment]
@BrunoScheufler ,

Thank. It is valuable to me! :joy:

**Comment by i0natan** [comment]
@oshliaer This is just great that as you translate you spot opportunities to improve, we'd love to see more

**Comment by oshliaer** [comment]
Usually, after the translation, I once again read the original and the finished translation. I did not learn English anywhere (only by myself) and some things are completely incomprehensible to me =)

**Pull request closed without merging**
