### PR TITLE
Brazilian portuguese

### PR DESCRIPTION
**Pull request by marcelosdm**
Hello everyone!

I think we're ready to push some Brazilian-Portuguese documentation!

I translated the README.brazilian-portuguese.md up to section 4.

This is not so much, but we'll get better soon!

Please, feel free to tell me if something is missing or if I should do more before I push it!

### CODE REVIEW

**Comment by js-kyle** [comment]
@marcelosdm Awesome, looks great! This is one for you @sagirk

**Comment by sagirk** [comment]
This looks to be an amazing, amazing start! 💯 Great job, @marcelosdm! 🎉

**Comment by marcelosdm** [comment]
@js-kyle @sagirk I'm so happy to read your comments!! Thank you so much! I've been woking with so much love on it!

**Comment by i0natan** [comment]
@marcelosdm Looks amazing!

**Comment by i0natan** [comment]
@sagirk What is the status of this PR? Not sure if pending some opener's comment or approval, I can help if busy on your part

**Comment by sagirk** [comment]
@i0natan I'm good with @marcelosdm's labor of love so far (thank you so much, Marcelo! ❤️).

We have the first four sections translated already, with two more to go. Do we wait until the entire homepage is translated or do we merge early since a bulk of the work is complete?

**Comment by BrunoScheufler** [comment]
@sagirk I'd say we can merge this as it's not going into the master branch, so any breaking changes won't cause side-effects anyway! Definitely looks great to me, awesome work @marcelosdm 💯

**Comment by i0natan** [comment]
@sagirk Agree with @BrunoScheufler

Shouldn't it now appear on the home page with the rest of the flags?

**Comment by BrunoScheufler** [comment]
@i0natan we could add a "work in progress" link to the translation section to let everybody preview the current progress of a translation!

**Comment by i0natan** [comment]
@BrunoScheufler All the other translations are even less established than this one, if we show other flags we should show Brazilian

**Comment by i0natan** [comment]
@sagirk I'll PR a Brazilian flag 

/remind me in 4 days

**Comment by marcelosdm** [comment]
> @BrunoScheufler All the other translations are even less established than this one, if we show other flags we should show Brazilian

Wow!!

I'm sorry to being away. I wasn't available last weeks.

Well, I'm so glad to read this!

**Pull request merged**
