### PR TITLE
Updated README.brazilian-portuguese.md

### PR DESCRIPTION
**Pull request by DouglasMV**
Translated section 4.2

### CODE REVIEW

**Comment by marcelosdm** [comment]
Great job @DouglasMV and welcome aboard! 👏👏👏

**Comment by marcelosdm** [comment]
By the way, @DouglasMV , it would be great if you join us to translate the other documents too!

What do you think? 😃

**Comment by DouglasMV** [comment]
Sure :)

**Comment by marcelosdm** [comment]
> Sure :)

Well, as you can see, I translated the *README* page. Now, we've got all the sections to dive in and do our work!

I would suggest for you to pick up a section, and translate its _Read More_ contents.

For example, if you can, the section 2.

What do you think?

**Comment by DouglasMV** [comment]
Sure, i will start working on section 2 Read More contents.

**Comment by marcelosdm** [comment]
@DouglasMV it looks like a promissing start!

**Comment by i0natan** [comment]
@DouglasMV @marcelosdm Amazing progress

**Pull request merged**
