### PR TITLE
Portuguese (Portugal) translation in progress

### PR DESCRIPTION
**Pull request by SandroMiguel**
I added the Portuguese flag in the translations in progress section.

### CODE REVIEW

**Comment by sagirk** [comment]
Good job so far, @SandroMiguel! Thanks for your efforts. I can see it is coming along nicely.

You might want to rebase your fork's branch against the upstream's master, though. There have been a good amount of changes merged in since you forked, including an entire new section on `Security Best Practices`.

**Comment by sagirk** [comment]
@SandroMiguel Yes, thanks! 💯

**Comment by sagirk** [comment]
Hi @SandroMiguel! 👋

Since it's been a while, just checking in on where we are now.

**Comment by i0natan** [comment]
@SandroMiguel @sagirk Seems we're very close here to a successful PR, shall we bring this to life?

**Comment by SandroMiguel** [comment]
Hello @i0natan and @sagirk, let me see if I have some time this weekend to resolve the conflicts.

**Comment by SandroMiguel** [comment]
Hello @i0natan and @sagirk, 
Please check my new PR
https://github.com/i0natan/nodebestpractices/pull/431
This one can be closed.

**Pull request closed without merging**
