### PR TITLE
Add sections 6 and 7 (in Brazilian Portuguese)

### PR DESCRIPTION
**Pull request by marcelosdm**
Here we go friends!

Very soon we're going to have the complete README file translated to Brazilian Portuguese!

### CODE REVIEW

**Comment by js-kyle** [comment]
awesome effort @marcelosdm 👍

**Comment by i0natan** [comment]
WOW @marcelosdm 🎂

**Comment by i0natan** [comment]
@sagirk @marcelosdm  Should we merge this to master?

**Comment by marcelosdm** [comment]
> @sagirk @marcelosdm Should we merge this to master?

@i0natan I think this is a great idea!

**Comment by sagirk** [comment]
[Discussion](https://github.com/i0natan/nodebestpractices/issues/223#issuecomment-469567657) for the work to land this on master: https://github.com/i0natan/nodebestpractices/issues/223

**Pull request merged**
