### PR TITLE
Feat/async await error management

### LINKED ISSUE #11: add async await error management example
it would be nice to have also an example with async/await in the error management section.

### PR DESCRIPTION
**Pull request by phra**
fixes #11

### CODE REVIEW

**Comment by i0natan** [comment]
@phra great idea to add promises and async-await examples.

Maybe we can start with simple and short examples that show:
1. Simple promise with 2-3 statements and a catch clause
2. Simple async-wait call to existing promise with a catch clause
3. Then the more advanced and long examples

p.s. shouldn't "increasing" be "decreasing"?

**Comment by phra** [comment]
i've added more examples.

**Comment by i0natan** [comment]
@phra reviewing in 1-2 days, thanks again

**Comment by i0natan** [comment]
@phra thanks for this. I have 1 conern: our core mission is curating content and providing dead-simple examples. If possible 3-4 lines of code. The provided examples are very comprehensive but too verbose for this style guide, any chance you shorten all the new examples into 3-4 lines? 

e.g. 
`
try{
promise.resolve(throw Error)
}
catch{error}{
//wont catch
}

try{
await promise.resolve(throw Error)
}
catch{error}{
//bingo!
}

`

**Comment by i0natan** [comment]
@BrunoScheufler can u take the lead here and suggest simple examples with @phra or alone?

**Comment by BrunoScheufler** [comment]
@phra Do you have shorter code examples in place? I could also help you out with shorter examples if you wanted so, just let me know!

**Comment by phra** [comment]
@BrunoScheufler i didn't had times in these days, but sure let's do this! i will give you collaborator access on my fork so you can update this PR. :smile:

**Comment by BrunoScheufler** [comment]
@phra @i0natan Apart from tiny changes I like the current code examples but as of now they are too long when seen as a whole. Maybe we could split the examples for the different cases with separate headings?

**Comment by phra** [comment]
@BrunoScheufler remember to accept the collaboration invitation! https://github.com/phra/nodebestpractices/invitations

**Comment by BrunoScheufler** [comment]
I think I can push commits to your fork anyways but let me accept that 😄

**Comment by sagirk** [comment]
@phra @BrunoScheufler @i0natan Seems this PR has remained stalled for nearly a year now. I'm trying to clear the backlog one PR at a time. What can we do to move this closer to being mergeable?

**Comment by phra** [comment]
at the moment i don't have time to review this, feel free to update the PR. let me know if i have to grant collaborator access to my fork.

**Comment by i0natan** [comment]
@sagirk @BrunoScheufler - Happy that we're doing this clean-up process.

I'd like to handle error management issues, unless someone else also interested. LMK and I'll update the routing table

**Comment by i0natan** [comment]
@phra I'm closing this based on our [1st writing principle here (Simplicity).](https://github.com/i0natan/nodebestpractices/blob/master/.operations/writing-guidelines.md)

Your examples are comprehensive and advanced, great stuff there, only to my judgment the idea of using async/await and promises are better communicated with simple examples.

Thanks for the contribution 👏 👏 👏

**Pull request closed without merging**
