### PR TITLE
Russian translation #4

### PR DESCRIPTION
**Pull request by oshliaer**
- [x] Security

### CODE REVIEW

**Comment by BrunoScheufler** [comment]
@oshliaer hey there! Saw that some time has passed and the changes are looking great 💯 Would you mind checking if the merge conflicts can be solved so we can go on and merge this in? 🚀 Thanks so much 🙌

**Comment by oshliaer** [comment]
Hi @BrunoScheufler !

Please let me a day for check it at again. It seems I lost a file.

**Comment by oshliaer** [comment]
Hi @BrunoScheufler!

It seems all fine now. This is a final step. This branch has the last updates and full Russian translation.

Except that I did not change the readme in part:

> Read in a different language: [CN**CN**](./../blob/master/README.chinese.md), [BR**BR**](./../blob/master/README.brazilian-portuguese.md) [(ES**ES**, FR**FR**, HE**HE**, KR**KR**, RU**RU** and TR**TR** in progress!)](./../#translations)

Please merge.

**Comment by i0natan** [comment]
@BrunoScheufler @js-kyle Any chance you can review & merge here? I'm on travel until next Wednesday

**Pull request merged**
