### PR TITLE
Merge BR translation into master

### PR DESCRIPTION
**Pull request by sagirk**
Merge BR translation into master, finally!

Please turn on the `No Whitespace` option during review.

image

/cc @marcelosdm 

Closes: https://github.com/i0natan/nodebestpractices/issues/223

### CODE REVIEW

**Comment by sagirk** [comment]
>This looks great 💯 Is there already a link in the main README that points to the new translation?

Just added [one](https://github.com/i0natan/nodebestpractices/pull/351/files#diff-04c6e90faac2675aa89e2176d2eec7d8R21).

Landing now!

**Comment by sagirk** [comment]
@BrunoScheufler The last review got dismissed after pushing a new commit. PTAL again.

**Comment by BrunoScheufler** [comment]
@i0natan could you sign this off? Would be great to have some final confirmation on this 👍

**Comment by i0natan** [comment]
> could you sign this off?

Sign what?

@BrunoScheufler

**Comment by BrunoScheufler** [comment]
@i0natan just meant that you should review the PR, so exactly what you did 😄

**Pull request merged**
