### PR TITLE
Brazilian Translation - Add Section 5

### PR DESCRIPTION
**Pull request by marcelosdm**
This PR adds section 5 to the Brazilian Translation.

### CODE REVIEW

**Comment by marcelosdm** [comment]
Hey friends!

I'm a little bit confused with those conflict files. Can anybody help me?

**Comment by BrunoScheufler** [comment]
@marcelosdm conflicts resolved 👍 You can comment once you're ready to merge 😃

**Comment by i0natan** [comment]
@BrunoScheufler You're the king. 

p.s. nobody is assigned, you're handling Brazilian (.operations-wise)?

**Comment by marcelosdm** [comment]
Hey @BrunoScheufler thanks a lot!!!

I'm ready to merge!

**Comment by BrunoScheufler** [comment]
@marcelosdm sorry for the delay, thanks for your great work 👍  I'll continue with reviewing the formal aspects and once we've got enough content, we'll go on to have some final proof-reading and make a final merge after that 🎉

**Comment by marcelosdm** [comment]
@BrunoScheufler thanks man! I'm learning a lot doing this job and I know I can improve it even more!

**Pull request merged**
