### PR TITLE
Fix grammar and typo in section 5.10

### PR DESCRIPTION
**Pull request by sagirk**
1. Fix grammar and a typo in section '5.10. Measure and guard the memory usage'
2. Add a link to Walmart Node.js Memory Leak from Joyent blog for context
3. Trim trailing spaces at EoL in README.md

### CODE REVIEW

**Comment by BrunoScheufler** [comment]
@sagirk great changes! As your other PR solved the trailing spaces you might resolve the issues connected to them in this PR if you can 👍 I'll be there if you need any help with it 😄

**Comment by sagirk** [comment]
@BrunoScheufler Thanks for merging the other PR! 👍 

I've rebased this against master. Please check if it is good to go now.

**Comment by sagirk** [comment]
Oops... looks like some unneeded stuff got in. Let me correct that real quick.

**Comment by sagirk** [comment]
@BrunoScheufler Okay, good to go now. Please take a look!

**Comment by BrunoScheufler** [comment]
@sagirk looks good now! Thank you!

**Pull request merged**
