### PR TITLE
Adding a Brazilian flag to translations

### PR DESCRIPTION
**Pull request by i0natan**
cc @marcelosdm

### CODE REVIEW

**Comment by i0natan** [comment]
@BrunoScheufler @marcelosdm I'm really clueless when it comes to graphic design, don't even know what flat means in this regard.

I guess what @marcelosdm suggested is better, can you PR that change?

**Comment by BrunoScheufler** [comment]
@i0natan no worries, we'll find the perfect look 😃 @marcelosdm your suggestion looks good, maybe you can open a PR for it 👍

**Comment by sagirk** [comment]
>Here's the link:
>flaticon.com/free-icon/brazil_206597

Looks good @marcelosdm. Can't wait for the PR! 💯

**Comment by marcelosdm** [comment]
Hello friends!

Great! I'm gonna do the PR right now!!

**Comment by i0natan** [comment]
@sagirk Any help needed here?

**Comment by sagirk** [comment]
@i0natan These changes have already been incorporated ~two months ago through @marcelosdm's https://github.com/i0natan/nodebestpractices/pull/283.

Since the changes are already in the README, it is alright to close this PR.

**Pull request closed without merging**
